#!/usr/bin/env tsx
/**
 * Interactive setup wizard for telegram-bridge.
 * Run with: pnpm setup
 */

import { createInterface } from 'readline/promises'
import { randomBytes } from 'crypto'
import { execSync, execFileSync } from 'child_process'
import fs from 'fs'
import path from 'path'
import os from 'os'

// ─── ANSI helpers ────────────────────────────────────────────────────────────

const c = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  blue: '\x1b[34m',
}

const ok = (msg: string) => console.log(`  ${c.green}✓${c.reset} ${msg}`)
const warn = (msg: string) => console.log(`  ${c.yellow}⚠${c.reset}  ${msg}`)
const fail = (msg: string) => console.log(`  ${c.red}✗${c.reset} ${msg}`)
const info = (msg: string) => console.log(`  ${c.dim}${msg}${c.reset}`)
const step = (n: number, total: number, msg: string) =>
  console.log(`\n${c.bold}${c.cyan}[${n}/${total}]${c.reset} ${c.bold}${msg}${c.reset}`)
const banner = (msg: string) => console.log(`\n${c.bold}${c.blue}${msg}${c.reset}`)

// ─── Readline wrapper ─────────────────────────────────────────────────────────

const rl = createInterface({ input: process.stdin, output: process.stdout })

async function ask(question: string, defaultValue?: string): Promise<string> {
  const hint = defaultValue ? ` ${c.dim}[${defaultValue}]${c.reset}` : ''
  const answer = await rl.question(`  ${c.yellow}?${c.reset} ${question}${hint}: `)
  return answer.trim() || defaultValue || ''
}

async function confirm(question: string, defaultYes = false): Promise<boolean> {
  const hint = defaultYes ? 'Y/n' : 'y/N'
  const answer = await rl.question(`  ${c.yellow}?${c.reset} ${question} (${hint}): `)
  if (!answer.trim()) return defaultYes
  return answer.trim().toLowerCase().startsWith('y')
}

// ─── Telegram API helpers ─────────────────────────────────────────────────────

interface TelegramResponse<T> {
  ok: boolean
  result?: T
  description?: string
}

interface Update {
  update_id: number
  message?: {
    message_id: number
    chat: { id: number; username?: string; first_name?: string }
    text?: string
  }
}

async function telegramGet<T>(token: string, method: string, params: Record<string, string | number> = {}): Promise<TelegramResponse<T>> {
  const url = new URL(`https://api.telegram.org/bot${token}/${method}`)
  for (const [k, v] of Object.entries(params)) url.searchParams.set(k, String(v))
  const res = await fetch(url.toString())
  return res.json() as Promise<TelegramResponse<T>>
}

async function validateBotToken(token: string): Promise<{ valid: boolean; username?: string }> {
  try {
    const res = await telegramGet<{ username: string }>(token, 'getMe')
    if (res.ok && res.result) return { valid: true, username: res.result.username }
    return { valid: false }
  } catch {
    return { valid: false }
  }
}

async function detectChatId(token: string, timeoutSeconds = 120): Promise<number | null> {
  // Get current offset to skip any old pending updates
  const initial = await telegramGet<Update[]>(token, 'getUpdates', { limit: 1 })
  const updates = initial.result ?? []
  const offset = updates.length > 0 ? (updates[updates.length - 1]!.update_id + 1) : 0

  const deadline = Date.now() + timeoutSeconds * 1000

  while (Date.now() < deadline) {
    const remaining = Math.ceil((deadline - Date.now()) / 1000)
    const pollTimeout = Math.min(30, remaining)
    if (pollTimeout <= 0) break

    try {
      const res = await telegramGet<Update[]>(token, 'getUpdates', {
        offset,
        timeout: pollTimeout,
        allowed_updates: 'message',
      })
      const newUpdates = res.result ?? []
      if (newUpdates.length > 0 && newUpdates[0]?.message) {
        return newUpdates[0].message.chat.id
      }
    } catch {
      // Network hiccup — retry
      await new Promise(r => setTimeout(r, 2000))
    }
  }

  return null
}

// ─── File helpers ─────────────────────────────────────────────────────────────

function writeEnv(values: Record<string, string | number>): void {
  const lines = [
    '# Generated by telegram-bridge setup wizard',
    `# Created: ${new Date().toISOString()}`,
    '',
  ]
  for (const [key, value] of Object.entries(values)) {
    lines.push(`${key}=${value}`)
  }
  fs.writeFileSync('.env', lines.join('\n') + '\n', { mode: 0o600 })
}

function detectShellRcFile(): string {
  const shell = process.env['SHELL'] ?? ''
  if (shell.includes('zsh')) return path.join(os.homedir(), '.zshrc')
  return path.join(os.homedir(), '.bashrc')
}

function addEnvToShell(rcFile: string, vars: Record<string, string>): boolean {
  const marker = '# telegram-bridge'
  const existing = fs.existsSync(rcFile) ? fs.readFileSync(rcFile, 'utf8') : ''

  if (existing.includes(marker)) return false // Already added

  const block = [
    '',
    marker,
    ...Object.entries(vars).map(([k, v]) => `export ${k}="${v}"`),
    '',
  ].join('\n')

  fs.appendFileSync(rcFile, block)
  return true
}

const CLAUDE_MD_MARKER = '## Telegram Bridge'

function buildClaudeMdBlock(installDir: string): string {
  const cliPath = path.join(installDir, 'claude-sdk', 'dist', 'cli.js')
  return `
## Telegram Bridge

A local bridge running at \`${installDir}\` lets you send updates to the user via Telegram and read their replies bidirectionally.

**Activate only when the user explicitly asks you to connect.**

### CLI

\`\`\`bash
node ${cliPath} <command>
\`\`\`

| Command | What it does |
|---------|-------------|
| \`status\` | Check server and session state |
| \`connect\` | Start session — bot becomes active |
| \`disconnect\` | End session — bot goes silent |
| \`send "text"\` | Send a message to the user on Telegram |
| \`send-photo <path|url> ["caption"]\` | Send an image |
| \`inbox\` | Read queued messages from the user (JSON) |
| \`read <id>\` | Mark a message as read |

### Workflow

1. \`connect\` → sends "🟢 Claude connected." to the user
2. Work autonomously; call \`send\` at key milestones
3. Call \`inbox\` periodically to check for user replies
4. Call \`read <id>\` to acknowledge each message
5. \`disconnect\` when done → sends "🔴 Session closed."

**Disconnect triggers**: inbox message containing "stop", "disconnect", "bye", "pause".
`
}

function updateClaudeMd(installDir: string): { updated: boolean; created: boolean } {
  const claudeMdPath = path.join(os.homedir(), '.claude', 'CLAUDE.md')
  const block = buildClaudeMdBlock(installDir)

  if (!fs.existsSync(claudeMdPath)) {
    fs.mkdirSync(path.dirname(claudeMdPath), { recursive: true })
    fs.writeFileSync(claudeMdPath, `# Claude Global Configuration\n${block}`)
    return { updated: false, created: true }
  }

  const existing = fs.readFileSync(claudeMdPath, 'utf8')
  if (existing.includes(CLAUDE_MD_MARKER)) {
    return { updated: false, created: false } // Already present
  }

  fs.appendFileSync(claudeMdPath, block)
  return { updated: true, created: false }
}

// ─── Systemd helper ───────────────────────────────────────────────────────────

function buildSystemdUnit(installDir: string): string {
  const nodePath = process.execPath
  return `[Unit]
Description=Telegram Bridge
After=network.target

[Service]
Type=simple
User=${os.userInfo().username}
WorkingDirectory=${installDir}
ExecStart=${nodePath} dist/index.js
Restart=always
RestartSec=5
EnvironmentFile=${installDir}/.env

[Install]
WantedBy=multi-user.target
`
}

// ─── Main wizard ──────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.clear()
  console.log(`${c.bold}${c.blue}
  ████████╗███████╗██╗      ███████╗ ██████╗ ██████╗  █████╗ ███╗   ███╗
     ██╔══╝██╔════╝██║      ██╔════╝██╔════╝ ██╔══██╗██╔══██╗████╗ ████║
     ██║   █████╗  ██║█████╗█████╗  ██║  ███╗██████╔╝███████║██╔████╔██║
     ██║   ██╔══╝  ██║╚════╝██╔══╝  ██║   ██║██╔══██╗██╔══██║██║╚██╔╝██║
     ██║   ███████╗███████╗ ███████╗╚██████╔╝██║  ██║██║  ██║██║ ╚═╝ ██║
     ╚═╝   ╚══════╝╚══════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝
                         BRIDGE — Setup Wizard
${c.reset}`)

  // Guard: must be run from the repo root
  if (!fs.existsSync('package.json') || !fs.existsSync('src/index.ts')) {
    fail('Run this script from the telegram-bridge repo root.')
    process.exit(1)
  }

  const installDir = process.cwd()
  const TOTAL_STEPS = 6

  // ── Check for existing .env ────────────────────────────────────────────────
  if (fs.existsSync('.env')) {
    warn('.env already exists.')
    const overwrite = await confirm('Overwrite and reconfigure?', false)
    if (!overwrite) {
      console.log('\n  Nothing changed. Exiting.\n')
      rl.close()
      return
    }
  }

  // ── Step 1: Node.js version ───────────────────────────────────────────────
  step(1, TOTAL_STEPS, 'Prerequisites')
  const nodeVersion = process.versions.node
  const major = parseInt(nodeVersion.split('.')[0]!, 10)
  if (major < 20) {
    fail(`Node.js 20+ required (found ${nodeVersion}). Install via nvm: nvm install 20`)
    rl.close()
    process.exit(1)
  }
  ok(`Node.js ${nodeVersion}`)

  // ── Step 2: API Key ───────────────────────────────────────────────────────
  step(2, TOTAL_STEPS, 'API Key')
  info('Generating a secure 32-byte API key...')
  const apiKey = randomBytes(32).toString('hex')
  ok(`API_KEY generated  ${c.dim}(${apiKey.slice(0, 8)}…)${c.reset}`)

  // ── Step 3: Telegram Bot Token ────────────────────────────────────────────
  step(3, TOTAL_STEPS, 'Telegram Bot Token')
  info('Open Telegram → search @BotFather → send /newbot → copy the token.')
  info('')

  let botToken = ''
  let botUsername = ''
  while (true) {
    botToken = await ask('Paste your bot token')
    if (!botToken) { fail('Token cannot be empty.'); continue }

    process.stdout.write(`  ${c.dim}Validating token with Telegram API…${c.reset}\r`)
    const check = await validateBotToken(botToken)
    process.stdout.write(' '.repeat(60) + '\r')

    if (check.valid) {
      botUsername = check.username ?? 'unknown'
      ok(`Bot @${botUsername} verified`)
      break
    }

    fail('Token rejected by Telegram. Check for typos and try again.')
  }

  // ── Step 4: Chat ID (auto-detected) ───────────────────────────────────────
  step(4, TOTAL_STEPS, 'Your Telegram Chat ID')
  info(`Open Telegram, find your bot @${botUsername}, and send it any message.`)
  info('Waiting up to 2 minutes…')
  info('')

  const chatId = await detectChatId(botToken, 120)

  if (!chatId) {
    fail('Timed out waiting for a message.')
    info('')
    info('You can find your Chat ID manually:')
    info(`  curl "https://api.telegram.org/bot${botToken}/getUpdates" | jq '.result[0].message.chat.id'`)
    const manual = await ask('Enter your Chat ID manually')
    const parsed = parseInt(manual, 10)
    if (isNaN(parsed)) {
      fail('Invalid Chat ID. Exiting.')
      rl.close()
      process.exit(1)
    }
    ok(`Chat ID: ${parsed}`)
    await runRemainingSteps(installDir, apiKey, botToken, parsed, TOTAL_STEPS)
  } else {
    ok(`Chat ID detected: ${chatId}`)
    await runRemainingSteps(installDir, apiKey, botToken, chatId, TOTAL_STEPS)
  }

  rl.close()
}

async function runRemainingSteps(
  installDir: string,
  apiKey: string,
  botToken: string,
  chatId: number,
  TOTAL_STEPS: number,
): Promise<void> {

  // ── Step 5: Config ────────────────────────────────────────────────────────
  step(5, TOTAL_STEPS, 'Configuration')

  const portStr = await ask('Server port', '3001')
  const port = parseInt(portStr, 10) || 3001

  const timeoutStr = await ask('Session auto-expire after N minutes of inactivity', '30')
  const timeout = parseInt(timeoutStr, 10) || 30

  writeEnv({
    API_KEY: apiKey,
    TELEGRAM_BOT_TOKEN: botToken,
    TELEGRAM_CHAT_ID: chatId,
    PORT: port,
    SESSION_TIMEOUT_MINUTES: timeout,
    NODE_ENV: 'production',
  })
  ok('.env created  (mode 600 — readable only by you)')

  // Build
  info('Building TypeScript…')
  try {
    execFileSync('pnpm', ['build'], { stdio: 'pipe' })
    ok('Build complete')
  } catch (err) {
    const output = err instanceof Error && 'stderr' in err
      ? (err as NodeJS.ErrnoException & { stderr: Buffer }).stderr?.toString()
      : String(err)
    fail(`Build failed:\n${output}`)
    process.exit(1)
  }

  // Shell profile
  const rcFile = detectShellRcFile()
  const added = addEnvToShell(rcFile, {
    TELEGRAM_BRIDGE_URL: `http://localhost:${port}`,
    TELEGRAM_BRIDGE_API_KEY: apiKey,
  })
  if (added) {
    ok(`Shell env vars added to ${rcFile}`)
  } else {
    warn(`Shell env vars already present in ${rcFile} — skipped`)
  }

  // CLAUDE.md
  const { updated, created } = updateClaudeMd(installDir)
  if (created) ok('~/.claude/CLAUDE.md created with bridge instructions')
  else if (updated) ok('~/.claude/CLAUDE.md updated with bridge instructions')
  else warn('~/.claude/CLAUDE.md already has the bridge section — skipped')

  // ── Step 6: Autostart ─────────────────────────────────────────────────────
  step(6, TOTAL_STEPS, 'Autostart (optional)')

  const wantSystemd = await confirm('Set up systemd service so the bridge starts on boot?', false)

  if (wantSystemd) {
    const unitContent = buildSystemdUnit(installDir)
    const unitPath = '/tmp/telegram-bridge.service'
    fs.writeFileSync(unitPath, unitContent)

    console.log('')
    info('Run these commands to install the systemd service:')
    console.log('')
    console.log(`    ${c.cyan}sudo cp ${unitPath} /etc/systemd/system/telegram-bridge.service${c.reset}`)
    console.log(`    ${c.cyan}sudo systemctl daemon-reload${c.reset}`)
    console.log(`    ${c.cyan}sudo systemctl enable --now telegram-bridge${c.reset}`)
    console.log('')
    info(`Service file written to: ${unitPath}`)
  }

  // ── Done ─────────────────────────────────────────────────────────────────
  console.log(`
${c.bold}${c.green}  ✓ Setup complete!${c.reset}

  ${c.bold}Start the server:${c.reset}
    pnpm start

  ${c.bold}Test it:${c.reset}
    node claude-sdk/dist/cli.js status

  ${c.bold}Reload your shell to pick up the new env vars:${c.reset}
    source ${detectShellRcFile()}

  ${c.bold}Then from any Claude Code session:${c.reset}
    node ${installDir}/claude-sdk/dist/cli.js connect
`)
}

main().catch((err: Error) => {
  console.error(`\n${c.red}Fatal:${c.reset} ${err.message}`)
  rl.close()
  process.exit(1)
})
